name: Tâche Planifiée

# Déclencheurs : automatique via Cron et manuel via Workflow Dispatch
on:
  schedule:
    # Syntaxe Cron : Minute (00) Heure (09) Jour-du-mois (*) Mois (*) Jour-de-la-semaine (1-5 = Lundi à Vendredi)
    - cron: '0 9 * * 1-5'

  # Permet de lancer le workflow manuellement depuis l'interface GitHub
  workflow_dispatch:

jobs:
  execution-planifiee:
    runs-on: ubuntu-latest

    steps:
      - name: Message d'exécution
        run: echo "Ce workflow s'exécute automatiquement à 9h UTC ou a été lancé manuellement par ${{ github.actor }}."
